### ISSUE TITLE
The yhat is all nan 

### ISSUE THREAD

**Issue by yeran7** [Dewald928/DeepFlarePred#1]
I am training the TCN model using your project, but the output of the infer_model function in main_TCN_Liu.py is nan, I can't solve the problem, could you please help me to solve the problem?

**Comment by Dewald928** [comment]
Thanks for your interest! 

So the model is getting data and training?
Does the MLP work? 
I haven't worked on the TCN, in a long time.
I should redo the code in something like pytorch lightning, because it's a bit of a mess. Sorry about that.

**Comment by yeran7** [comment]
I changed the config of the TCN model, so it can work properly now, thanks for your reply!

**Comment by Dewald928** [comment]
Excellent, sorry about the messy code :)
